---
title: Hoofd- en kleine letters wisselen met Python
hero_image: images/banner.png
description: Wissel hoofd- en kleine letters in tekst met Python
original_url:
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: true
curriculum:
interests:
technologies: "python"
site_areas:
steps:
  - 
    title: Wisselen van hoofd- en kleine letters

