---
title: Cambiando mayúsculas y minúsculas con Python
hero_image: images/banner.png
description: Cambiar las mayúsculas y minúsculas de cadenas con Python
original_url:
theme: rojo #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: true
curriculum:
interests:
technologies: "python"
site_areas:
steps:
  - 
    title: Cambiando mayúsculas y minúsculas

